/**
 * Email delivery for trend reports via Resend.
 *
 * Sends beautifully formatted HTML emails for daily and weekly reports.
 * Called from Inngest report generation functions after the report is stored.
 */
import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)

const FROM_ADDRESS = 'Molly <molly@mollymemo.com>'

interface SendReportEmailParams {
  to: string
  reportType: 'daily' | 'weekly'
  title: string
  content: string
  windowStart: string
  windowEnd: string
  itemCount: number
  projectsMentioned: { name: string }[] | null
}

export async function sendReportEmail(params: SendReportEmailParams) {
  const { to, reportType, title, content, windowStart, windowEnd, itemCount, projectsMentioned } = params

  const html = buildReportEmailHtml({
    reportType,
    title,
    content,
    windowStart,
    windowEnd,
    itemCount,
    projectsMentioned,
  })

  const subject = reportType === 'weekly'
    ? `Weekly Roundup: ${title}`
    : `Daily Report: ${title}`

  const { error } = await resend.emails.send({
    from: FROM_ADDRESS,
    to,
    subject,
    html,
  })

  if (error) {
    throw new Error(`Resend error: ${error.message}`)
  }
}

// --- HTML email template ---

function buildReportEmailHtml(params: Omit<SendReportEmailParams, 'to'>): string {
  const { reportType, title, content, windowStart, windowEnd, itemCount, projectsMentioned } = params

  const windowLabel = formatDateRange(windowStart, windowEnd)
  const typeBadgeColor = reportType === 'weekly' ? '#6366f1' : '#0ea5e9'
  const typeLabel = reportType === 'weekly' ? 'Weekly Roundup' : 'Daily Report'

  const projectsHtml = projectsMentioned?.length
    ? projectsMentioned.map(p =>
        `<span style="display:inline-block;background:#f1f5f9;color:#475569;padding:2px 8px;border-radius:4px;font-size:12px;margin-right:4px;">${escapeHtml(p.name)}</span>`
      ).join(' ')
    : ''

  const contentHtml = markdownToHtml(content)

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escapeHtml(title)}</title>
</head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;">
<tr><td align="center" style="padding:32px 16px;">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;">

<!-- Header -->
<tr><td style="padding:24px 32px;background:#1e293b;border-radius:12px 12px 0 0;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
  <tr>
    <td><span style="font-size:18px;font-weight:700;color:#f8fafc;letter-spacing:-0.02em;">MollyMemo</span></td>
    <td align="right"><span style="display:inline-block;background:${typeBadgeColor};color:#fff;padding:4px 10px;border-radius:6px;font-size:12px;font-weight:600;text-transform:uppercase;">${typeLabel}</span></td>
  </tr>
  </table>
</td></tr>

<!-- Title + meta -->
<tr><td style="padding:28px 32px 16px;background:#fff;">
  <h1 style="margin:0 0 12px;font-size:22px;font-weight:700;color:#0f172a;line-height:1.3;">${escapeHtml(title)}</h1>
  <p style="margin:0;font-size:13px;color:#94a3b8;">
    ${escapeHtml(windowLabel)} &middot; ${itemCount} item${itemCount !== 1 ? 's' : ''} analyzed
  </p>
  ${projectsHtml ? `<div style="margin-top:10px;">${projectsHtml}</div>` : ''}
</td></tr>

<!-- Divider -->
<tr><td style="padding:0 32px;background:#fff;">
  <hr style="border:none;border-top:1px solid #e2e8f0;margin:0;">
</td></tr>

<!-- Content -->
<tr><td style="padding:20px 32px 28px;background:#fff;font-size:15px;line-height:1.7;color:#334155;">
  ${contentHtml}
</td></tr>

<!-- Footer -->
<tr><td style="padding:20px 32px;background:#f1f5f9;border-radius:0 0 12px 12px;text-align:center;">
  <p style="margin:0;font-size:12px;color:#94a3b8;">
    Generated by <a href="https://mollymemo.com/reports" style="color:#6366f1;text-decoration:none;">MollyMemo</a>
  </p>
</td></tr>

</table>
</td></tr>
</table>
</body>
</html>`
}

// --- Helpers ---

function formatDateRange(start: string, end: string): string {
  const s = new Date(start)
  const e = new Date(end)
  const opts: Intl.DateTimeFormatOptions = { month: 'short', day: 'numeric' }

  if (s.getMonth() === e.getMonth() && s.getFullYear() === e.getFullYear()) {
    return `${s.toLocaleDateString('en-US', opts)}–${e.getDate()}`
  }
  return `${s.toLocaleDateString('en-US', opts)} – ${e.toLocaleDateString('en-US', opts)}`
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function markdownToHtml(md: string): string {
  return md
    .split('\n')
    .map(line => {
      if (line.startsWith('### '))
        return `<h3 style="margin:20px 0 8px;font-size:16px;font-weight:600;color:#0f172a;">${escapeHtml(line.slice(4))}</h3>`
      if (line.startsWith('## '))
        return `<h2 style="margin:24px 0 10px;font-size:18px;font-weight:700;color:#0f172a;">${escapeHtml(line.slice(3))}</h2>`
      if (line.startsWith('- '))
        return `<p style="margin:4px 0;padding-left:16px;">&bull; ${inlineFormat(line.slice(2))}</p>`
      if (line.trim() === '') return '<br>'
      return `<p style="margin:8px 0;">${inlineFormat(line)}</p>`
    })
    .join('\n')
}

function inlineFormat(text: string): string {
  return escapeHtml(text).replace(
    /\*\*(.+?)\*\*/g,
    '<strong style="color:#0f172a;">$1</strong>'
  )
}
